# **IPL Exploratory Data Analysis (2008-2024)**

## Final summary

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import chi2_contingency

In [24]:
df=pd.read_csv('matches.csv')
df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   str
 2   city             1044 non-null   str
 3   date             1095 non-null   str
 4   match_type       1095 non-null   str
 5   player_of_match  1090 non-null   str
 6   venue            1095 non-null   str
 7   team1            1095 non-null   str
 8   team2            1095 non-null   str
 9   toss_winner      1095 non-null   str
 10  toss_decision    1095 non-null   str
 11  winner           1090 non-null   str
 12  result           1095 non-null   str
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   str
 17  method           21 non-null     str
 18  umpire1          1095 non-null   str
 19  umpire2          1095 non-null   str
dtypes: float64(3), int64(1), str(16)
memory usage: 171.2 KB

From df.info() we can has the most NaN values followed by city and we also have NaN values from player_of_match,result_margin,winner and both target_runs and target_overs

In [26]:
null_series = df.isnull().sum()
null_pct = (null_series / len(df) * 100).round(2)
null_pct

id                  0.00
season              0.00
city                4.66
date                0.00
match_type          0.00
player_of_match     0.46
venue               0.00
team1               0.00
team2               0.00
toss_winner         0.00
toss_decision       0.00
winner              0.46
result              0.00
result_margin       1.74
target_runs         0.27
target_overs        0.27
super_over          0.00
method             98.08
umpire1             0.00
umpire2             0.00
dtype: float64

Based on the above percentages method column has the most amount of NaNs that column is used to determine if the team won by dls or not here i will conver the NaN values to 'normal' instead of dropping the column

For the remaining NaN values i would opt to just drop the columns as they have are relatively rare(<5%)

In [27]:
df['method']=df['method'].fillna('normal')
df=df.dropna(axis=0,how='any')

In [28]:
null_series = df.isnull().sum()
null_pct = (null_series / len(df) * 100).round(2)
null_pct

id                 0.0
season             0.0
city               0.0
date               0.0
match_type         0.0
player_of_match    0.0
venue              0.0
team1              0.0
team2              0.0
toss_winner        0.0
toss_decision      0.0
winner             0.0
result             0.0
result_margin      0.0
target_runs        0.0
target_overs       0.0
super_over         0.0
method             0.0
umpire1            0.0
umpire2            0.0
dtype: float64

Ok so now moving on

In [30]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,1028.0,895782.877432,372056.819568,335982.0,548317.75,980938.0,1254078.25,1426312.0
result_margin,1028.0,17.026265,21.569306,1.0,6.00,8.0,20.00,146.0
target_runs,1028.0,165.656615,33.605098,43.0,146.00,166.0,187.00,288.0
target_overs,1028.0,19.758949,1.562059,5.0,20.00,20.0,20.00,20.0